// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/fountain.dart';
import 'api/qr.dart';
import 'api/simple.dart';
import 'api/vcode.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 321567387;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_vloom',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  bool crateApiFountainFountainDecoderAddPacket({
    required FountainDecoder that,
    required List<int> packet,
  });

  FountainDecoder crateApiFountainFountainDecoderNew({
    required List<int> otiBytes,
  });

  int crateApiFountainFountainDecoderPacketsReceived({
    required FountainDecoder that,
  });

  Uint8List? crateApiFountainFountainDecoderPayload({
    required FountainDecoder that,
  });

  BigInt crateApiFountainFountainDecoderPayloadSize({
    required FountainDecoder that,
  });

  FountainEncoder crateApiFountainFountainEncoderNew({
    required List<int> payload,
    required int packetSize,
    required int extraRepair,
  });

  Uint8List crateApiFountainFountainEncoderOtiBytes({
    required FountainEncoder that,
  });

  Uint8List crateApiFountainFountainEncoderPacket({
    required FountainEncoder that,
    required int i,
  });

  int crateApiFountainFountainEncoderPacketCount({
    required FountainEncoder that,
  });

  Future<VcodeAcquireReport> crateApiVcodeVcodeRxAcquire({
    required VcodeRx that,
    required List<int> y,
    required int width,
    required int height,
    required int stride,
    required int rotationDeg,
    required bool thorough,
  });

  VcodeRx crateApiVcodeVcodeRxNew();

  Future<VcodeScanReport> crateApiVcodeVcodeRxScan({
    required VcodeRx that,
    required List<int> y,
    required int width,
    required int height,
    required int stride,
    required int rotationDeg,
    required double guideFrac,
    required bool debugDump,
  });

  void crateApiVcodeVcodeRxSeed({
    required VcodeRx that,
    required int rot,
    required int gridW,
    required int gridH,
    required List<double> corners,
  });

  void crateApiVcodeVcodeRxSetLayout({
    required VcodeRx that,
    required int gridW,
    required int gridH,
  });

  int crateApiVcodeVcodeTxFrameCount({required VcodeTx that});

  VcodeFrameImage crateApiVcodeVcodeTxFrameGray({
    required VcodeTx that,
    required int i,
  });

  VcodeTx crateApiVcodeVcodeTxNew({
    required List<int> payload,
    required int extraRepair,
    required int gridW,
    required int gridH,
    required int bitsPerCell,
  });

  int crateApiVcodeVcodeTxPacketCount({required VcodeTx that});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  QrMatrix crateApiQrMakeQr({
    required List<int> data,
    required String ec,
    required int minVersion,
  });

  VcodeFile? crateApiVcodeVcodeUnwrapFile({required List<int> buf});

  Uint8List? crateApiVcodeVcodeUnwrapPayload({required List<int> payload});

  Uint8List crateApiVcodeVcodeWrapFile({
    required String name,
    required String mime,
    required List<int> data,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FountainDecoder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FountainDecoder;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FountainDecoderPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FountainEncoder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FountainEncoder;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FountainEncoderPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_VcodeRx;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_VcodeRx;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_VcodeRxPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_VcodeTx;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_VcodeTx;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_VcodeTxPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  bool crateApiFountainFountainDecoderAddPacket({
    required FountainDecoder that,
    required List<int> packet,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(packet, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFountainFountainDecoderAddPacketConstMeta,
        argValues: [that, packet],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainDecoderAddPacketConstMeta =>
      const TaskConstMeta(
        debugName: "FountainDecoder_add_packet",
        argNames: ["that", "packet"],
      );

  @override
  FountainDecoder crateApiFountainFountainDecoderNew({
    required List<int> otiBytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(otiBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFountainFountainDecoderNewConstMeta,
        argValues: [otiBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainDecoderNewConstMeta =>
      const TaskConstMeta(
        debugName: "FountainDecoder_new",
        argNames: ["otiBytes"],
      );

  @override
  int crateApiFountainFountainDecoderPacketsReceived({
    required FountainDecoder that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFountainFountainDecoderPacketsReceivedConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainDecoderPacketsReceivedConstMeta =>
      const TaskConstMeta(
        debugName: "FountainDecoder_packets_received",
        argNames: ["that"],
      );

  @override
  Uint8List? crateApiFountainFountainDecoderPayload({
    required FountainDecoder that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFountainFountainDecoderPayloadConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainDecoderPayloadConstMeta =>
      const TaskConstMeta(
        debugName: "FountainDecoder_payload",
        argNames: ["that"],
      );

  @override
  BigInt crateApiFountainFountainDecoderPayloadSize({
    required FountainDecoder that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFountainFountainDecoderPayloadSizeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainDecoderPayloadSizeConstMeta =>
      const TaskConstMeta(
        debugName: "FountainDecoder_payload_size",
        argNames: ["that"],
      );

  @override
  FountainEncoder crateApiFountainFountainEncoderNew({
    required List<int> payload,
    required int packetSize,
    required int extraRepair,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(payload, serializer);
          sse_encode_u_16(packetSize, serializer);
          sse_encode_u_32(extraRepair, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFountainFountainEncoderNewConstMeta,
        argValues: [payload, packetSize, extraRepair],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainEncoderNewConstMeta =>
      const TaskConstMeta(
        debugName: "FountainEncoder_new",
        argNames: ["payload", "packetSize", "extraRepair"],
      );

  @override
  Uint8List crateApiFountainFountainEncoderOtiBytes({
    required FountainEncoder that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFountainFountainEncoderOtiBytesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainEncoderOtiBytesConstMeta =>
      const TaskConstMeta(
        debugName: "FountainEncoder_oti_bytes",
        argNames: ["that"],
      );

  @override
  Uint8List crateApiFountainFountainEncoderPacket({
    required FountainEncoder that,
    required int i,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
            that,
            serializer,
          );
          sse_encode_u_32(i, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFountainFountainEncoderPacketConstMeta,
        argValues: [that, i],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainEncoderPacketConstMeta =>
      const TaskConstMeta(
        debugName: "FountainEncoder_packet",
        argNames: ["that", "i"],
      );

  @override
  int crateApiFountainFountainEncoderPacketCount({
    required FountainEncoder that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFountainFountainEncoderPacketCountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainEncoderPacketCountConstMeta =>
      const TaskConstMeta(
        debugName: "FountainEncoder_packet_count",
        argNames: ["that"],
      );

  @override
  Future<VcodeAcquireReport> crateApiVcodeVcodeRxAcquire({
    required VcodeRx that,
    required List<int> y,
    required int width,
    required int height,
    required int stride,
    required int rotationDeg,
    required bool thorough,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeRx(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(y, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_u_32(stride, serializer);
          sse_encode_u_32(rotationDeg, serializer);
          sse_encode_bool(thorough, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vcode_acquire_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeRxAcquireConstMeta,
        argValues: [that, y, width, height, stride, rotationDeg, thorough],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeRxAcquireConstMeta =>
      const TaskConstMeta(
        debugName: "VcodeRx_acquire",
        argNames: [
          "that",
          "y",
          "width",
          "height",
          "stride",
          "rotationDeg",
          "thorough",
        ],
      );

  @override
  VcodeRx crateApiVcodeVcodeRxNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeRx,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeRxNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeRxNewConstMeta =>
      const TaskConstMeta(debugName: "VcodeRx_new", argNames: []);

  @override
  Future<VcodeScanReport> crateApiVcodeVcodeRxScan({
    required VcodeRx that,
    required List<int> y,
    required int width,
    required int height,
    required int stride,
    required int rotationDeg,
    required double guideFrac,
    required bool debugDump,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeRx(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(y, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_u_32(stride, serializer);
          sse_encode_u_32(rotationDeg, serializer);
          sse_encode_f_64(guideFrac, serializer);
          sse_encode_bool(debugDump, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vcode_scan_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeRxScanConstMeta,
        argValues: [
          that,
          y,
          width,
          height,
          stride,
          rotationDeg,
          guideFrac,
          debugDump,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeRxScanConstMeta => const TaskConstMeta(
    debugName: "VcodeRx_scan",
    argNames: [
      "that",
      "y",
      "width",
      "height",
      "stride",
      "rotationDeg",
      "guideFrac",
      "debugDump",
    ],
  );

  @override
  void crateApiVcodeVcodeRxSeed({
    required VcodeRx that,
    required int rot,
    required int gridW,
    required int gridH,
    required List<double> corners,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeRx(
            that,
            serializer,
          );
          sse_encode_u_32(rot, serializer);
          sse_encode_u_8(gridW, serializer);
          sse_encode_u_8(gridH, serializer);
          sse_encode_list_prim_f_32_loose(corners, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeRxSeedConstMeta,
        argValues: [that, rot, gridW, gridH, corners],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeRxSeedConstMeta => const TaskConstMeta(
    debugName: "VcodeRx_seed",
    argNames: ["that", "rot", "gridW", "gridH", "corners"],
  );

  @override
  void crateApiVcodeVcodeRxSetLayout({
    required VcodeRx that,
    required int gridW,
    required int gridH,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeRx(
            that,
            serializer,
          );
          sse_encode_u_8(gridW, serializer);
          sse_encode_u_8(gridH, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeRxSetLayoutConstMeta,
        argValues: [that, gridW, gridH],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeRxSetLayoutConstMeta =>
      const TaskConstMeta(
        debugName: "VcodeRx_set_layout",
        argNames: ["that", "gridW", "gridH"],
      );

  @override
  int crateApiVcodeVcodeTxFrameCount({required VcodeTx that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeTxFrameCountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeTxFrameCountConstMeta =>
      const TaskConstMeta(debugName: "VcodeTx_frame_count", argNames: ["that"]);

  @override
  VcodeFrameImage crateApiVcodeVcodeTxFrameGray({
    required VcodeTx that,
    required int i,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
            that,
            serializer,
          );
          sse_encode_u_32(i, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vcode_frame_image,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeTxFrameGrayConstMeta,
        argValues: [that, i],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeTxFrameGrayConstMeta =>
      const TaskConstMeta(
        debugName: "VcodeTx_frame_gray",
        argNames: ["that", "i"],
      );

  @override
  VcodeTx crateApiVcodeVcodeTxNew({
    required List<int> payload,
    required int extraRepair,
    required int gridW,
    required int gridH,
    required int bitsPerCell,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(payload, serializer);
          sse_encode_u_32(extraRepair, serializer);
          sse_encode_u_8(gridW, serializer);
          sse_encode_u_8(gridH, serializer);
          sse_encode_u_8(bitsPerCell, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeTxNewConstMeta,
        argValues: [payload, extraRepair, gridW, gridH, bitsPerCell],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeTxNewConstMeta => const TaskConstMeta(
    debugName: "VcodeTx_new",
    argNames: ["payload", "extraRepair", "gridW", "gridH", "bitsPerCell"],
  );

  @override
  int crateApiVcodeVcodeTxPacketCount({required VcodeTx that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeTxPacketCountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeTxPacketCountConstMeta =>
      const TaskConstMeta(
        debugName: "VcodeTx_packet_count",
        argNames: ["that"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  QrMatrix crateApiQrMakeQr({
    required List<int> data,
    required String ec,
    required int minVersion,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_String(ec, serializer);
          sse_encode_u_8(minVersion, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qr_matrix,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiQrMakeQrConstMeta,
        argValues: [data, ec, minVersion],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQrMakeQrConstMeta => const TaskConstMeta(
    debugName: "make_qr",
    argNames: ["data", "ec", "minVersion"],
  );

  @override
  VcodeFile? crateApiVcodeVcodeUnwrapFile({required List<int> buf}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(buf, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_vcode_file,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeUnwrapFileConstMeta,
        argValues: [buf],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeUnwrapFileConstMeta =>
      const TaskConstMeta(debugName: "vcode_unwrap_file", argNames: ["buf"]);

  @override
  Uint8List? crateApiVcodeVcodeUnwrapPayload({required List<int> payload}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(payload, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeUnwrapPayloadConstMeta,
        argValues: [payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeUnwrapPayloadConstMeta =>
      const TaskConstMeta(
        debugName: "vcode_unwrap_payload",
        argNames: ["payload"],
      );

  @override
  Uint8List crateApiVcodeVcodeWrapFile({
    required String name,
    required String mime,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(mime, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeWrapFileConstMeta,
        argValues: [name, mime, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeWrapFileConstMeta => const TaskConstMeta(
    debugName: "vcode_wrap_file",
    argNames: ["name", "mime", "data"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FountainDecoder => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FountainDecoder => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FountainEncoder => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FountainEncoder => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_VcodeRx => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeRx;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_VcodeRx => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeRx;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_VcodeTx => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_VcodeTx => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx;

  @protected
  FountainDecoder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FountainDecoderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FountainEncoder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FountainEncoderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VcodeRx
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeRx(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VcodeRxImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VcodeTx
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VcodeTxImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FountainDecoder
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FountainDecoderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VcodeRx
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeRx(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VcodeRxImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FountainDecoder
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FountainDecoderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FountainEncoder
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FountainEncoderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VcodeTx
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VcodeTxImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FountainDecoder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FountainDecoderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FountainEncoder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FountainEncoderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VcodeRx
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeRx(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VcodeRxImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VcodeTx
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VcodeTxImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  VcodeFile dco_decode_box_autoadd_vcode_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_vcode_file(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  VcodeFile? dco_decode_opt_box_autoadd_vcode_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_vcode_file(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  QrMatrix dco_decode_qr_matrix(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return QrMatrix(
      size: dco_decode_u_32(arr[0]),
      modules: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VcodeAcquireReport dco_decode_vcode_acquire_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return VcodeAcquireReport(
      detected: dco_decode_bool(arr[0]),
      rot: dco_decode_u_32(arr[1]),
      gridW: dco_decode_u_8(arr[2]),
      gridH: dco_decode_u_8(arr[3]),
      blocksOk: dco_decode_u_32(arr[4]),
      blocksTotal: dco_decode_u_32(arr[5]),
      corners: dco_decode_list_prim_f_32_strict(arr[6]),
      imgW: dco_decode_u_32(arr[7]),
      imgH: dco_decode_u_32(arr[8]),
    );
  }

  @protected
  VcodeFile dco_decode_vcode_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VcodeFile(
      name: dco_decode_String(arr[0]),
      mime: dco_decode_String(arr[1]),
      data: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  VcodeFrameImage dco_decode_vcode_frame_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VcodeFrameImage(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      pixels: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  VcodeScanReport dco_decode_vcode_scan_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 17)
      throw Exception('unexpected arr length: expect 17 but see ${arr.length}');
    return VcodeScanReport(
      detected: dco_decode_bool(arr[0]),
      tracked: dco_decode_bool(arr[1]),
      frameSeq: dco_decode_u_32(arr[2]),
      oti: dco_decode_list_prim_u_8_strict(arr[3]),
      packets: dco_decode_list_list_prim_u_8_strict(arr[4]),
      blocksOk: dco_decode_u_32(arr[5]),
      blocksTotal: dco_decode_u_32(arr[6]),
      error: dco_decode_opt_String(arr[7]),
      corners: dco_decode_list_prim_f_32_strict(arr[8]),
      imgW: dco_decode_u_32(arr[9]),
      imgH: dco_decode_u_32(arr[10]),
      rot: dco_decode_u_32(arr[11]),
      rotateUs: dco_decode_u_32(arr[12]),
      decodeUs: dco_decode_u_32(arr[13]),
      debugGray: dco_decode_opt_list_prim_u_8_strict(arr[14]),
      debugW: dco_decode_u_32(arr[15]),
      debugH: dco_decode_u_32(arr[16]),
    );
  }

  @protected
  FountainDecoder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FountainDecoderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FountainEncoder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FountainEncoderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VcodeRx
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeRx(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VcodeRxImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VcodeTx
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VcodeTxImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FountainDecoder
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FountainDecoderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VcodeRx
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeRx(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VcodeRxImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FountainDecoder
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FountainDecoderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FountainEncoder
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FountainEncoderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VcodeTx
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VcodeTxImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FountainDecoder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FountainDecoderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FountainEncoder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FountainEncoderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VcodeRx
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeRx(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VcodeRxImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VcodeTx
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VcodeTxImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  VcodeFile sse_decode_box_autoadd_vcode_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_vcode_file(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  VcodeFile? sse_decode_opt_box_autoadd_vcode_file(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_vcode_file(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QrMatrix sse_decode_qr_matrix(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_size = sse_decode_u_32(deserializer);
    var var_modules = sse_decode_list_prim_u_8_strict(deserializer);
    return QrMatrix(size: var_size, modules: var_modules);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VcodeAcquireReport sse_decode_vcode_acquire_report(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_detected = sse_decode_bool(deserializer);
    var var_rot = sse_decode_u_32(deserializer);
    var var_gridW = sse_decode_u_8(deserializer);
    var var_gridH = sse_decode_u_8(deserializer);
    var var_blocksOk = sse_decode_u_32(deserializer);
    var var_blocksTotal = sse_decode_u_32(deserializer);
    var var_corners = sse_decode_list_prim_f_32_strict(deserializer);
    var var_imgW = sse_decode_u_32(deserializer);
    var var_imgH = sse_decode_u_32(deserializer);
    return VcodeAcquireReport(
      detected: var_detected,
      rot: var_rot,
      gridW: var_gridW,
      gridH: var_gridH,
      blocksOk: var_blocksOk,
      blocksTotal: var_blocksTotal,
      corners: var_corners,
      imgW: var_imgW,
      imgH: var_imgH,
    );
  }

  @protected
  VcodeFile sse_decode_vcode_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_mime = sse_decode_String(deserializer);
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    return VcodeFile(name: var_name, mime: var_mime, data: var_data);
  }

  @protected
  VcodeFrameImage sse_decode_vcode_frame_image(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_pixels = sse_decode_list_prim_u_8_strict(deserializer);
    return VcodeFrameImage(
      width: var_width,
      height: var_height,
      pixels: var_pixels,
    );
  }

  @protected
  VcodeScanReport sse_decode_vcode_scan_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_detected = sse_decode_bool(deserializer);
    var var_tracked = sse_decode_bool(deserializer);
    var var_frameSeq = sse_decode_u_32(deserializer);
    var var_oti = sse_decode_list_prim_u_8_strict(deserializer);
    var var_packets = sse_decode_list_list_prim_u_8_strict(deserializer);
    var var_blocksOk = sse_decode_u_32(deserializer);
    var var_blocksTotal = sse_decode_u_32(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_corners = sse_decode_list_prim_f_32_strict(deserializer);
    var var_imgW = sse_decode_u_32(deserializer);
    var var_imgH = sse_decode_u_32(deserializer);
    var var_rot = sse_decode_u_32(deserializer);
    var var_rotateUs = sse_decode_u_32(deserializer);
    var var_decodeUs = sse_decode_u_32(deserializer);
    var var_debugGray = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_debugW = sse_decode_u_32(deserializer);
    var var_debugH = sse_decode_u_32(deserializer);
    return VcodeScanReport(
      detected: var_detected,
      tracked: var_tracked,
      frameSeq: var_frameSeq,
      oti: var_oti,
      packets: var_packets,
      blocksOk: var_blocksOk,
      blocksTotal: var_blocksTotal,
      error: var_error,
      corners: var_corners,
      imgW: var_imgW,
      imgH: var_imgH,
      rot: var_rot,
      rotateUs: var_rotateUs,
      decodeUs: var_decodeUs,
      debugGray: var_debugGray,
      debugW: var_debugW,
      debugH: var_debugH,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    FountainDecoder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FountainDecoderImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    FountainEncoder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FountainEncoderImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeRx(
    VcodeRx self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VcodeRxImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    VcodeTx self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VcodeTxImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    FountainDecoder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FountainDecoderImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeRx(
    VcodeRx self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VcodeRxImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    FountainDecoder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FountainDecoderImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    FountainEncoder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FountainEncoderImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    VcodeTx self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VcodeTxImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    FountainDecoder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FountainDecoderImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    FountainEncoder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FountainEncoderImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeRx(
    VcodeRx self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VcodeRxImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    VcodeTx self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VcodeTxImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_vcode_file(
    VcodeFile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vcode_file(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_vcode_file(
    VcodeFile? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_vcode_file(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_qr_matrix(QrMatrix self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.size, serializer);
    sse_encode_list_prim_u_8_strict(self.modules, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vcode_acquire_report(
    VcodeAcquireReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.detected, serializer);
    sse_encode_u_32(self.rot, serializer);
    sse_encode_u_8(self.gridW, serializer);
    sse_encode_u_8(self.gridH, serializer);
    sse_encode_u_32(self.blocksOk, serializer);
    sse_encode_u_32(self.blocksTotal, serializer);
    sse_encode_list_prim_f_32_strict(self.corners, serializer);
    sse_encode_u_32(self.imgW, serializer);
    sse_encode_u_32(self.imgH, serializer);
  }

  @protected
  void sse_encode_vcode_file(VcodeFile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.mime, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
  }

  @protected
  void sse_encode_vcode_frame_image(
    VcodeFrameImage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.pixels, serializer);
  }

  @protected
  void sse_encode_vcode_scan_report(
    VcodeScanReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.detected, serializer);
    sse_encode_bool(self.tracked, serializer);
    sse_encode_u_32(self.frameSeq, serializer);
    sse_encode_list_prim_u_8_strict(self.oti, serializer);
    sse_encode_list_list_prim_u_8_strict(self.packets, serializer);
    sse_encode_u_32(self.blocksOk, serializer);
    sse_encode_u_32(self.blocksTotal, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_list_prim_f_32_strict(self.corners, serializer);
    sse_encode_u_32(self.imgW, serializer);
    sse_encode_u_32(self.imgH, serializer);
    sse_encode_u_32(self.rot, serializer);
    sse_encode_u_32(self.rotateUs, serializer);
    sse_encode_u_32(self.decodeUs, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.debugGray, serializer);
    sse_encode_u_32(self.debugW, serializer);
    sse_encode_u_32(self.debugH, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class FountainDecoderImpl extends RustOpaque implements FountainDecoder {
  // Not to be used by end users
  FountainDecoderImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FountainDecoderImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_FountainDecoder,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_FountainDecoder,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_FountainDecoderPtr,
  );

  /// パケットを 1 つ追加。復元できれば内部に payload を保存し true を返す。
  bool addPacket({required List<int> packet}) => RustLib.instance.api
      .crateApiFountainFountainDecoderAddPacket(that: this, packet: packet);

  /// これまでに投入した (採用された) パケット数。
  int packetsReceived() => RustLib.instance.api
      .crateApiFountainFountainDecoderPacketsReceived(that: this);

  /// 復元済みなら payload を返す (未復元なら None)。
  Uint8List? payload() =>
      RustLib.instance.api.crateApiFountainFountainDecoderPayload(that: this);

  /// 想定 payload サイズ (バイト)。
  BigInt payloadSize() => RustLib.instance.api
      .crateApiFountainFountainDecoderPayloadSize(that: this);
}

@sealed
class FountainEncoderImpl extends RustOpaque implements FountainEncoder {
  // Not to be used by end users
  FountainEncoderImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FountainEncoderImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_FountainEncoder,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_FountainEncoder,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_FountainEncoderPtr,
  );

  /// 受信側に渡す 12 バイトの OTI (decoder 構築に必須)。
  Uint8List otiBytes() =>
      RustLib.instance.api.crateApiFountainFountainEncoderOtiBytes(that: this);

  /// i 番目のシリアライズ済みパケット (4 バイト ID + symbol_size バイト data)。
  Uint8List packet({required int i}) => RustLib.instance.api
      .crateApiFountainFountainEncoderPacket(that: this, i: i);

  /// 生成済みパケットの総数。送信側はこの値で循環表示する (Dart 側 int)。
  int packetCount() => RustLib.instance.api
      .crateApiFountainFountainEncoderPacketCount(that: this);
}

@sealed
class VcodeRxImpl extends RustOpaque implements VcodeRx {
  // Not to be used by end users
  VcodeRxImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  VcodeRxImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_VcodeRx,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_VcodeRx,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_VcodeRxPtr,
  );

  /// 位置合わせ: 画面全体を多位置 × スケール × 全回転で sweep し、中央から外れた/傾いた
  /// コードでも初回取得する。1 回きりの重い処理なので scan() とは別 (非同期ワーカー実行)。
  /// 成功時は seed() に渡すべき rot・格子・4 隅を返す。self.last は変更しない (確認後に seed する)。
  /// thorough=false は locate_code 由来の 1 点のみ試す軽量版 (自動起動用、数十 ms)。
  /// thorough=true は従来の全 sweep も行う (手動ボタン用、数秒かかってよい)。
  /// 自動起動で全 sweep を回すと、見つからないとき数秒間フレーム処理が止まり、
  /// 「周期的にフリーズする」体感になる (実機で 7〜9 秒の停止として観測)。
  Future<VcodeAcquireReport> acquire({
    required List<int> y,
    required int width,
    required int height,
    required int stride,
    required int rotationDeg,
    required bool thorough,
  }) => RustLib.instance.api.crateApiVcodeVcodeRxAcquire(
    that: this,
    y: y,
    width: width,
    height: height,
    stride: stride,
    rotationDeg: rotationDeg,
    thorough: thorough,
  );

  /// カメラの Y プレーンから vcode をスキャンする。
  /// トラッキング成功時は report.tracked = true。
  /// 注: sync にしない。非同期 (Rust ワーカースレッド実行) にすることで
  /// UI isolate をブロックせず、カメラプレビューのカクつきを防ぐ。
  Future<VcodeScanReport> scan({
    required List<int> y,
    required int width,
    required int height,
    required int stride,
    required int rotationDeg,
    required double guideFrac,
    required bool debugDump,
  }) => RustLib.instance.api.crateApiVcodeVcodeRxScan(
    that: this,
    y: y,
    width: width,
    height: height,
    stride: stride,
    rotationDeg: rotationDeg,
    guideFrac: guideFrac,
    debugDump: debugDump,
  );

  /// acquire で得た (回転, 格子, 4 隅) をトラッキングの種として設定する。
  /// これ以降 scan() は最初からこの位置に追従した状態で始まる (中央ガイド枠に頼らない)。
  void seed({
    required int rot,
    required int gridW,
    required int gridH,
    required List<double> corners,
  }) => RustLib.instance.api.crateApiVcodeVcodeRxSeed(
    that: this,
    rot: rot,
    gridW: gridW,
    gridH: gridH,
    corners: corners,
  );

  /// 探索するレイアウトを 1 つに固定する (grid_w = 0 で解除)。
  /// 候補総当たりは初回検出とacquireのコストを候補数に比例して増やすので、送信側の格子が
  /// 分かっている場合 (計測・自動掃引・能力交換後) はこれで固定する。
  void setLayout({required int gridW, required int gridH}) => RustLib
      .instance
      .api
      .crateApiVcodeVcodeRxSetLayout(that: this, gridW: gridW, gridH: gridH);
}

@sealed
class VcodeTxImpl extends RustOpaque implements VcodeTx {
  // Not to be used by end users
  VcodeTxImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  VcodeTxImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_VcodeTx,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_VcodeTx,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_VcodeTxPtr,
  );

  /// ループ 1 周のフレーム数 (= ceil(packet_count / ブロック数))
  int frameCount() =>
      RustLib.instance.api.crateApiVcodeVcodeTxFrameCount(that: this);

  /// i 番目のフレーム画像を生成する。パケットは循環割り当てなので全フレームが満杯になる。
  VcodeFrameImage frameGray({required int i}) =>
      RustLib.instance.api.crateApiVcodeVcodeTxFrameGray(that: this, i: i);

  int packetCount() =>
      RustLib.instance.api.crateApiVcodeVcodeTxPacketCount(that: this);
}
