// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `candidates`, `fail_acquire`, `fail`, `rotate_y_plane`, `success`

/// Fountain 復元結果のエンドツーエンド CRC-32 を検証して剥がす。
/// None = ブロック CRC をすり抜けたゴミパケットで復元結果が破損している
/// (受信側はデコーダを作り直して受信を続行すべき)。
Uint8List? vcodeUnwrapPayload({required List<int> payload}) =>
    RustLib.instance.api.crateApiVcodeVcodeUnwrapPayload(payload: payload);

/// 元のファイル名/MIME をヘッダに埋めて送信ペイロードを作る (受信側で元名・種別を復元する用)。
/// これを VcodeTx に渡す payload とする。
Uint8List vcodeWrapFile({
  required String name,
  required String mime,
  required List<int> data,
}) => RustLib.instance.api.crateApiVcodeVcodeWrapFile(
  name: name,
  mime: mime,
  data: data,
);

/// 復元済みペイロードから元のファイル名/MIME/中身を取り出す。ヘッダが無ければ None。
VcodeFile? vcodeUnwrapFile({required List<int> buf}) =>
    RustLib.instance.api.crateApiVcodeVcodeUnwrapFile(buf: buf);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VcodeRx>>
abstract class VcodeRx implements RustOpaqueInterface {
  /// 位置合わせ: 画面全体を多位置 × スケール × 全回転で sweep し、中央から外れた/傾いた
  /// コードでも初回取得する。1 回きりの重い処理なので scan() とは別 (非同期ワーカー実行)。
  /// 成功時は seed() に渡すべき rot・格子・4 隅を返す。self.last は変更しない (確認後に seed する)。
  /// thorough=false は locate_code 由来の 1 点のみ試す軽量版 (自動起動用、数十 ms)。
  /// thorough=true は従来の全 sweep も行う (手動ボタン用、数秒かかってよい)。
  /// 自動起動で全 sweep を回すと、見つからないとき数秒間フレーム処理が止まり、
  /// 「周期的にフリーズする」体感になる (実機で 7〜9 秒の停止として観測)。
  Future<VcodeAcquireReport> acquire({
    required List<int> y,
    required int width,
    required int height,
    required int stride,
    required int rotationDeg,
    required bool thorough,
  });

  factory VcodeRx() => RustLib.instance.api.crateApiVcodeVcodeRxNew();

  /// カメラの Y プレーンから vcode をスキャンする。
  /// トラッキング成功時は report.tracked = true。
  /// 注: sync にしない。非同期 (Rust ワーカースレッド実行) にすることで
  /// UI isolate をブロックせず、カメラプレビューのカクつきを防ぐ。
  Future<VcodeScanReport> scan({
    required List<int> y,
    required int width,
    required int height,
    required int stride,
    required int rotationDeg,
    required double guideFrac,
    required bool debugDump,
  });

  /// acquire で得た (回転, 格子, 4 隅) をトラッキングの種として設定する。
  /// これ以降 scan() は最初からこの位置に追従した状態で始まる (中央ガイド枠に頼らない)。
  void seed({
    required int rot,
    required int gridW,
    required int gridH,
    required List<double> corners,
  });

  /// 探索するレイアウトを 1 つに固定する (grid_w = 0 で解除)。
  /// 候補総当たりは初回検出とacquireのコストを候補数に比例して増やすので、送信側の格子が
  /// 分かっている場合 (計測・自動掃引・能力交換後) はこれで固定する。
  void setLayout({required int gridW, required int gridH});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VcodeTx>>
abstract class VcodeTx implements RustOpaqueInterface {
  /// ループ 1 周のフレーム数 (= ceil(packet_count / ブロック数))
  int frameCount();

  /// i 番目のフレーム画像を生成する。パケットは循環割り当てなので全フレームが満杯になる。
  VcodeFrameImage frameGray({required int i});

  /// payload を vcode 用に符号化する。extra_repair はリペアパケット追加数。
  /// grid_w x grid_h はブロック格子 (5x4=標準, 7x6=高密度)。
  /// bits_per_cell: 1=白黒 (packet 42B), 2=輝度4値 (packet 92B)。
  /// payload には先頭に CRC-32 が付与される (受信側は vcode_unwrap_payload で検証して剥がす)。
  factory VcodeTx({
    required List<int> payload,
    required int extraRepair,
    required int gridW,
    required int gridH,
    required int bitsPerCell,
  }) => RustLib.instance.api.crateApiVcodeVcodeTxNew(
    payload: payload,
    extraRepair: extraRepair,
    gridW: gridW,
    gridH: gridH,
    bitsPerCell: bitsPerCell,
  );

  int packetCount();
}

/// 位置合わせ (acquire) の結果。detected=true なら corners (回転後画像座標, tl,tr,br,bl の 8 値) と
/// rot・格子を seed() に渡すと、その位置に追従した状態で受信を始められる。中央ガイド枠に頼らない。
class VcodeAcquireReport {
  final bool detected;

  /// 検出時の回転 (seed に渡す)
  final int rot;
  final int gridW;
  final int gridH;
  final int blocksOk;
  final int blocksTotal;

  /// 回転後画像での 4 隅 [tl.x, tl.y, tr.x, tr.y, br.x, br.y, bl.x, bl.y]
  final Float32List corners;

  /// 回転後画像の寸法 (UI が corners を表示座標へ写すのに使う)
  final int imgW;
  final int imgH;

  const VcodeAcquireReport({
    required this.detected,
    required this.rot,
    required this.gridW,
    required this.gridH,
    required this.blocksOk,
    required this.blocksTotal,
    required this.corners,
    required this.imgW,
    required this.imgH,
  });

  @override
  int get hashCode =>
      detected.hashCode ^
      rot.hashCode ^
      gridW.hashCode ^
      gridH.hashCode ^
      blocksOk.hashCode ^
      blocksTotal.hashCode ^
      corners.hashCode ^
      imgW.hashCode ^
      imgH.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VcodeAcquireReport &&
          runtimeType == other.runtimeType &&
          detected == other.detected &&
          rot == other.rot &&
          gridW == other.gridW &&
          gridH == other.gridH &&
          blocksOk == other.blocksOk &&
          blocksTotal == other.blocksTotal &&
          corners == other.corners &&
          imgW == other.imgW &&
          imgH == other.imgH;
}

/// unwrap_file の Flutter 向けミラー。ヘッダが無ければ None (旧形式=従来処理へフォールバック)。
class VcodeFile {
  final String name;
  final String mime;
  final Uint8List data;

  const VcodeFile({required this.name, required this.mime, required this.data});

  @override
  int get hashCode => name.hashCode ^ mime.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VcodeFile &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          mime == other.mime &&
          data == other.data;
}

/// フレーム画像 (グレースケール、1 セル = 1 ピクセル)
class VcodeFrameImage {
  final int width;
  final int height;

  /// 0=黒, 255=白 の行優先グレースケール
  final Uint8List pixels;

  const VcodeFrameImage({
    required this.width,
    required this.height,
    required this.pixels,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ pixels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VcodeFrameImage &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          pixels == other.pixels;
}

/// スキャン結果。detected=false のとき error に理由 (デバッグログ用)。
class VcodeScanReport {
  final bool detected;

  /// トラッキング (前フレームからの追従) で検出したか (効果検証用)
  final bool tracked;
  final int frameSeq;
  final Uint8List oti;

  /// CRC が通ったブロックのペイロード (= シリアライズ済み RaptorQ パケット) 列
  final List<Uint8List> packets;
  final int blocksOk;
  final int blocksTotal;
  final String? error;

  /// 検出した 4 隅 (回転後画像座標, tl,tr,br,bl の 8 値)。UI が「今どこを読んでいるか」を
  /// 毎フレーム描くために返す。ScanResult が既に持つ値を渡すだけでコストはない。
  final Float32List corners;

  /// corners の座標系 (回転後画像の寸法と、その回転)
  final int imgW;
  final int imgH;
  final int rot;

  /// スキャン内訳 (マイクロ秒)。実機がカメラのフレーム間隔に追従できないとき、
  /// Y プレーンの回転コピーと探索・デコードのどちらが効いているかを切り分ける。
  final int rotateUs;
  final int decodeUs;

  /// debug_dump=true のとき、回転処理後のグレースケール画像 (PC 側解析用)
  final Uint8List? debugGray;
  final int debugW;
  final int debugH;

  const VcodeScanReport({
    required this.detected,
    required this.tracked,
    required this.frameSeq,
    required this.oti,
    required this.packets,
    required this.blocksOk,
    required this.blocksTotal,
    this.error,
    required this.corners,
    required this.imgW,
    required this.imgH,
    required this.rot,
    required this.rotateUs,
    required this.decodeUs,
    this.debugGray,
    required this.debugW,
    required this.debugH,
  });

  @override
  int get hashCode =>
      detected.hashCode ^
      tracked.hashCode ^
      frameSeq.hashCode ^
      oti.hashCode ^
      packets.hashCode ^
      blocksOk.hashCode ^
      blocksTotal.hashCode ^
      error.hashCode ^
      corners.hashCode ^
      imgW.hashCode ^
      imgH.hashCode ^
      rot.hashCode ^
      rotateUs.hashCode ^
      decodeUs.hashCode ^
      debugGray.hashCode ^
      debugW.hashCode ^
      debugH.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VcodeScanReport &&
          runtimeType == other.runtimeType &&
          detected == other.detected &&
          tracked == other.tracked &&
          frameSeq == other.frameSeq &&
          oti == other.oti &&
          packets == other.packets &&
          blocksOk == other.blocksOk &&
          blocksTotal == other.blocksTotal &&
          error == other.error &&
          corners == other.corners &&
          imgW == other.imgW &&
          imgH == other.imgH &&
          rot == other.rot &&
          rotateUs == other.rotateUs &&
          decodeUs == other.decodeUs &&
          debugGray == other.debugGray &&
          debugW == other.debugW &&
          debugH == other.debugH;
}
