[package]
name = "rust_lib_vloom"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.12.0"
vloom-fountain = { path = "../../fountain" }
vloom-vcode = { path = "../../vcode" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
